core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pasantia/', include('pasantia.urls', namespace="pasantia")),
    path('users/', include('accounts.urls', namespace="users")),
    path('', HomeView, name='home'),
    path('informacion/<post>/', viewInformation, name="info"),
    path('finalizados/post', postfinalizados, name="postfinalizados"),
    path('buscador/',buscador, name="buscador")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pasantia/urls.py
from django.urls import path

from .views import *

app_name = "pasantia"

urlpatterns = [
    path('create/post', HomeViewPostulacion, name="pasantia-edit"),
    path('create/postpasantia', Createpostpasantia, name='createpost'),
    path('modify/<pasantia>/', modificarPasantia, name="modpost"),
    path('create/registentidad',createEntidad, name="createntidad"),
    path('create/postulacion/<pasantia>', crearPostulacion, name='postulacion'),
    path('revpost/<pasantia>', revpost,name="rev_postulacion"),
    path('revdoc/<username>', revdoc, name="rev_doc"),
    path('postulacion/registro/',crearPostulacion, name='postulacionhecha'),
    path('sorteo/<pasantia>/', sorteo, name="sorteo"),
    path('<pasantia>/unidades', registrarunidades, name="registrounidades"),
    path('<pasantia>/unidades/<id>', registrarestudiantes, name="asignarestudiantes"),
    path('view/pdf/<body>/', pdfpasantia, name="verpdf"),
]

templates/pages/finalizados.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}Inicio Sistema de Pasantias{% endblock tittle %}

{% block content %}
<main>
   
    <div id="caja_presentacion" class="fila">
        <div class="presentacion_tabla">
            <div class="titulo">
                Pasantias
            </div>
            <div class="llenar">
                <table class="tablita">
                    <tr >
                        <th class="peq">
                            Nro
                        </th>
                        <th class="med">
                            Estado
                        </th>
                        <th>
                            Observaciones
                        </th>
                        <th class="peq">
                            Unidades
                        </th>
                    </tr>
                    {% for post in posts %}
                    <tr>
                        <td>
                            {{post.body}}
                        </td>
                        <td>
                            {{post.estado}}
                        </td>
                        <td style="TEXT-ALIGN:CENTER;">
                            {% if post.estado == 'FINALIZADO' %}   FALTA ASIGNACION {%else%} ASIGNACION COMPLETADA {% endif %}
                        </td>
                        <td>
                                {% if post.estado == 'ASIGNADO' %}
                                <a href="{% url 'pasantia:verpdf' post.body%}">Ver PDF</a>
                                {% else %}
                                <a href="{% url 'pasantia:registrounidades' post.body%}">Unidades</a>
                                {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
       </div>
    </div>
</main>
{% endblock content %}

templates/pages/finalizadosespecifico.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}Inicio Sistema de Pasantias{% endblock tittle %}

{% block content %}
    <main>
        <input type="checkbox" name="btn-1" id="btn-1" hidden>
        <input type="checkbox" name="btn-2" id="btn-2" hidden>
        <datalist id="e_2/2022">
            {% for postulante in postulantes %}
            <option value="{{postulante.estudiante.first_name}} {{postulante.estudiante.last_name}} {{postulante.estudiante.second_last_name}}"></option>
            {% endfor %}
        </datalist>
        <datalist id="e_1/2022">
            {% for postulante in postulantes %}
            <option value="{{postulante.estudiante.username}}"></option>
            {% endfor %}
        </datalist>
        <div id="caja_presentacion" class="fila">
            <div class="presentacion_tabla">
                <div class="titulo">
                    Pasantias
                </div>
                <div class="llenar">
                    <table class="tablita">
                        <tr >
                            <th class="peq">
                                Nro
                            </th>
                            <th class="med">
                                Estado
                            </th>
                            <th>
                                Observaciones
                            </th>
                            <th class="peq">
                                Unidades
                            </th>
                        </tr>
                        {% for post in posts %}
                        <tr>
                            <td>
                                {{post.body}}
                            </td>
                            <td>
                                {{post.estado}}
                            </td>
                            <td style="TEXT-ALIGN:CENTER;">
                                {% if post.estado == 'FINALIZADO' %}   FALTA ASIGNACION {%else%} ASIGNACION COMPLETADA {% endif %}
                            </td>
                            <td>
                                {% if post.estado == 'ASIGNADO' %}
                                <a href="">Ver PDF</a>
                                {% else %}
                                <a href="{% url 'pasantia:registrounidades' post.body%}">Unidades</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
           </div>
        </div>


        <div class="cont-modal">
            <div class="conten-modal">
                <h2>Unidades Pasantia {{pasantia.body}}</h2>
                <div class="tab_mod">
                    <table class="t2">
                        <tr class="cap">
                            <th>
                                Nombre
                            </th>
                            <th>
                                Cupos Disponibles
                            </th>
                            <th>
                                Botón
                            </th>
                        </tr>
                        {% for unidad in unidades %}
                        <tr>
                            <td>
                                {{unidad.nombre}}
                            </td>
                            <td>
                                {{unidad.cantidad}}
                            </td>
                            <td> 
                                    {% if unidad.estado == 'REVISION' %}  
                                    <a href= "{% url 'pasantia:asignarestudiantes' pasantia.body unidad.id%}">Asignar</a>
                                    {% else %}
                                    Asignacion completada
                                    {% endif %}
                            </td>
                        </tr>
                        {% endfor %}        
                    </table>
                </div>
                <div class="btn-cerrar2">
                    <label for="btn-1" class="boton_2">
                        Cerrar
                    </label>
                </div>
            </div>
            <label for="btn-1" class="cerrar-modal"></label>
        </div>
        
    </main>
    
    <script>
        var pas = "e_2/2022";
        var c =0;
        var auc=0;
        var xas=0;
        function as_es(i){
            pas=i;
        }
        function crear_l(n){
            auc=n;
            var b = document.getElementById("lis_est_u");
            var lis=document.getElementById(pas).childNodes;
            var j=0;
            

            

            for (let i = 0; i < lis.length; i++) {
                i++;
                const a = document.createElement("label");
                a.setAttribute("for",lis[i].value);
                a.setAttribute("class","label_largo");
                a.setAttribute("value",c);

                const sp= document.createElement("span");
                sp.textContent=lis[i].value+" :";
                a.appendChild(sp);

                const inp= document.createElement("input");
                inp.setAttribute("oninput","lista_checks(this.checked)");
                inp.setAttribute("type","checkbox");
                inp.setAttribute("class","rt");
                inp.setAttribute("value",lis[i].value);
                inp.setAttribute("name",j);
                inp.setAttribute("id",lis[i].value);
                a.appendChild(inp);
                b.appendChild(a);
                c=c+1;
                j++;
            }
            
        }
        function eli_l(){
            var d = document.querySelectorAll(".label_largo");
            for (let k = 0; k < d.length; k++) {
                d[k].remove();
            }
            c=0;
        }
        function lista_checks(g){
                if(g){
                    xas++;
                    if(xas==auc){
                        var dp = document.querySelector(".dis");
                        dp.className="boton_2 qw";
                        var tuy = document.querySelectorAll(".rt");
                        tuy.forEach(e => {
                            if(e.checked==false){
                                e.classList="rt oculto";
                            }
                        });
                    }
                }else{
                    xas--;
                    if(xas<auc){
                        var dp = document.querySelector(".qw");
                        dp.className="boton_2 dis oculto";
                        var tuy = document.querySelectorAll(".rt");
                        tuy.forEach(e => {
                            if(e.checked==false){
                                e.classList="rt";
                            }
                        });
                    }
                }
        }
        function envia(){
            var b = document.getElementById("lis_est_u");
            
            b.submit();
            eli_l();
        }
        
    </script>
    {% endblock content %}

templates/pages/finalizadosespecificounidad.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}Inicio Sistema de Pasantias{% endblock tittle %}

{% block content %}
    <main>
        <input type="checkbox" name="btn-1" id="btn-1" hidden>
        <input type="checkbox" name="btn-2" id="btn-2" hidden>
        <datalist id="e_2/2022">
            {% for postulante in postulantes %}
            <option value="{{postulante.estudiante.first_name}} {{postulante.estudiante.last_name}} {{postulante.estudiante.second_last_name}}"></option>
            {% endfor %}
        </datalist>
        <datalist id="e_1/2022">
            {% for postulante in postulantes %}
            <option value="{{postulante.estudiante.username}}"></option>
            {% endfor %}
        </datalist>
        <div id="caja_presentacion" class="fila">
            <div class="presentacion_tabla">
                <div class="titulo">
                    Pasantias
                </div>
                <div class="llenar">
                    <table class="tablita">
                        <tr >
                            <th class="peq">
                                Nro
                            </th>
                            <th class="med">
                                Estado
                            </th>
                            <th>
                                Observaciones
                            </th>
                            <th class="peq">
                                Unidades
                            </th>
                        </tr>
                        {% for post in posts %}
                        <tr>
                            <td>
                                {{post.body}}
                            </td>
                            <td>
                                {{post.estado}}
                            </td>
                            <td style="TEXT-ALIGN:CENTER;">
                                {% if post.estado == 'FINALIZADO' %}   FALTA ASIGNACION {%else%} ASIGNACION COMPLETADA {% endif %}
                            </td>
                            <td>
                                {% if post.estado == 'ASIGNADO' %}
                                <a href="">Ver PDF</a>
                                {% else %}
                                <a href="{% url 'pasantia:registrounidades' post.body%}">Unidades</a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
           </div>
        </div>


        <div class="cont-modal">
            <div class="conten-modal">
                <h2>Unidades Pasantia {{pasantia.body}}</h2>
                <div class="tab_mod">
                    <table class="t2">
                        <tr class="cap">
                            <th>
                                Nombre
                            </th>
                            <th>
                                Cupos Disponibles
                            </th>
                            <th>
                                Botón
                            </th>
                        </tr>
                        {% for unidad in unidades %}
                        <tr>
                            <td>
                                {{unidad.nombre}}
                            </td>
                            <td>
                                {{unidad.cantidad}}
                            </td>
                            <td>
                                    {% if unidad.estado == 'REVISION' %}
                                    <a href= "{% url 'pasantia:asignarestudiantes' pasantia.body unidad.id%}">Asignar</a>
                                    {% else %}
                                    Asignacion completada
                                    {% endif %}
                            </td>
                        </tr>
                        {% endfor %}        
                    </table>
                </div>
                <div class="btn-cerrar2">
                    <label for="btn-1" class="boton_2">
                        Cerrar
                    </label>
                </div>
            </div>
            <label for="btn-1" class="cerrar-modal"></label>
        </div>
        
        

        <div class="cont-modal1">
            <div class="conten-modal">
                <h2>Pasantia {{pasantia.body}}</h2>
                <h4>Unidad {{unidad.nombre}}</h4>
                <br>
                <div >
                    <form method="POST" id="lis_est_u">
                        {% csrf_token %}
                        <label for="nom_uni" class="oculto">
                            <input type="text" id="nom_uni" name="nom_uni" value="{{unidad.id}}">
                        </label>
                    </form>
                </div>
                <div class="btn-cerrar2" >
                    
                </div>
                <div class="btn-cerrar2">
                    <label onclick="envia()" for="" class="boton_2 oculto dis" style="margin-right: 20px;">
                        Asignar
                    </label>
                    <label onclick="eli_l()" for="btn-2" class="boton_2">
                        Cerrar
                    </label>
                </div>
            </div>
            <label onclick="eli_l()" for="btn-2" class="cerrar-modal"></label>
        </div>
    </main>
    
    <script>
        var pas = "e_2/2022";
        var c =0;
        var auc=0;
        var xas=0;
        crear_l({{unidad.cantidad}});
        function as_es(i){
            pas=i;
        }
        function crear_l(n){
            auc=n;
            var b = document.getElementById("lis_est_u");
            var lis=document.getElementById(pas).childNodes;
            var lis1=document.getElementById("e_1/2022").childNodes;
            var j=0;
            for (let i = 0; i < lis.length; i++) {
                i++;
                const a = document.createElement("label");
                a.setAttribute("for",lis[i].value);
                a.setAttribute("class","label_largo");
                a.setAttribute("value",c);

                const sp= document.createElement("span");
                sp.textContent=lis[i].value+" :";
                a.appendChild(sp);

                const inp= document.createElement("input");
                inp.setAttribute("oninput","lista_checks(this.checked)");
                inp.setAttribute("type","checkbox");
                inp.setAttribute("class","rt");
                inp.setAttribute("value",lis1[i].value);
                inp.setAttribute("name",j);
                inp.setAttribute("id",lis[i].value);
                a.appendChild(inp);
                b.appendChild(a);
                c=c+1;
                j++;
            }
            
        }
        function eli_l(){
            var d = document.querySelectorAll(".label_largo");
            for (let k = 1; k < d.length; k++) {
                d[k].remove();
            }
            c=0;
        }
        function lista_checks(g){
                if(g){
                    xas++;
                    if(xas==auc){
                        var dp = document.querySelector(".dis");
                        dp.className="boton_2 qw";
                        var tuy = document.querySelectorAll(".rt");
                        tuy.forEach(e => {
                            if(e.checked==false){
                                e.classList="rt oculto";
                            }
                        });
                    }
                }else{
                    xas--;
                    if(xas<auc){
                        var dp = document.querySelector(".qw");
                        dp.className="boton_2 dis oculto";
                        var tuy = document.querySelectorAll(".rt");
                        tuy.forEach(e => {
                            if(e.checked==false){
                                e.classList="rt";
                            }
                        });
                    }
                }
        }
        function envia(){
            var b = document.getElementById("lis_est_u");
            
            b.submit();
            eli_l();
        }
        
    </script>
    {% endblock content %}

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}Inicio Sistema de Pasantias{% endblock tittle %}

{% block content %}

<main>
    <input type="checkbox" name="btn-b" id="btn-b">
   <div id="buscador">  
        <div class="titulo">
            Buscador
        </div>
        <div id="busc">
            <form action="{% url 'buscador' %}" method="POST">
                {% csrf_token %}
                <label for="unidad">
                    <span>Nro pasantia:</span>
                    <input type="text" name="nro" id="unidad">
                </label>
                <label for="fecha_ini">
                    <span>Fecha Publicacion:</span>
                    <input type="date" name="fecha_ini" id="fecha_ini">
                </label>
                <label for="fecha_fin">
                    <span>Fecha Limite:</span>
                    <input type="date" name="fecha_fin" id="fecha_fin">
                </label>
                <label for="estado">
                    <span>Estado de Pasantia:</span>
                    <input list="opc_est" name="estado" id="estado"> 
                <datalist id="opc_est">
                    <option>REVISION</option>
                    <option>FINALIZADO</option>
                    <option>ASIGNADO</option>
                </datalist>
                <div id="busc_btn">
                    <a><button type="submit">Buscar</button></a>
                </div>
            </form>
        </div>
        <br>
        
    </div>
    <div id="caja_presentacion">
{% for post in posts %}<div class="caja_pasantia">
            <span id="cua"></span>
            <div class="contenido">
                <h2>Nro {{post.body}}</h2>
                <div class="logo_unidad" >
                    <img class="logo_u" src="{{post.entidad_pert.image.url}}" alt="logo_unidad">
                </div>
                <label for="">
                    <span>Publicado: {{post.created_on}}</span>
                </label>
                <label for="">
                    <span>Limite: {{post.fecha_limite}}</span>
                </label>
                <label for="">
                    <span>Entidad: {{post.entidad_pert.nombre}}</span>
                </label>
                <label for="">
                    <span>Total Insc: {{post.cantidad_insc}}</span>
                </label>
                
                {% if user.tipo == 'administrador' %}
                <!--<a href="{% url 'pasantia:sorteo' post.body%}">Sortear</a>-->
                <a href="{% url 'pasantia:modpost' post.body%}">Modificar</a> 
                <a href="{% url 'pasantia:rev_postulacion' post.body%}">Ver Postulantes</a> 
                {% else %}
                <a href="{% url 'info' post.body%}">Saber Mas</a> 
                {% endif %}
                
            </div>
        </div>
{% endfor %}</div>
</main>

{% endblock content %}

templates/pages/informacion.html
{% extends 'base.html' %}
{% load static %}

{% load i18n %}

{% block tittle %}Informacion {{post.body}}{% endblock tittle %}

{% block content %}
<main>
    <div id="caja_presentacion">
        <div id="caja_info">
            <div class="titulo">
                Informacion Pasatia {{post.body}}
            </div>
            <div class="pdf_con">
                <object
                    data='{{post.file.url}}'
                    type="application/pdf"
                    height="250"
                    width="550"
                    >
                    <iframe
                        src='{{post.file.url}}'
                        height="250"
                        width="250"
                        >
                        <p>Este navegador no soporta PDF</p>
                    </iframe>
                </object>
                {% if user.tipo == 'estudiante' %}
                <a href="{% url 'pasantia:postulacion' post.body%}" class="btn blue"><span>Postularme</span></a>
                {% endif %}
                
            </div>
        </div>
    </div>
</main>
{% endblock content %}