accounts/urls.py
from django.urls import path

from .views import *

app_name = "accounts"

urlpatterns = [
    path('profile/edit', EditProfile, name="edit"),
    path('profile/documents', DocumentUploadProfile, name="profile-document"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pasantia/', include('pasantia.urls', namespace="pasantia")),
    path('users/', include('accounts.urls', namespace="users")),
    path('', HomeView, name='home'),
    path('informacion/<post>/', viewInformation, name="info"),
    path('finalizados/post', postfinalizados, name="postfinalizados"),
    path('buscador/',buscador, name="buscador")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pasantia/urls.py
from django.urls import path

from .views import *

app_name = "pasantia"

urlpatterns = [
    path('create/post', HomeViewPostulacion, name="pasantia-edit"),
    path('create/postpasantia', Createpostpasantia, name='createpost'),
    path('modify/<pasantia>/', modificarPasantia, name="modpost"),
    path('create/registentidad',createEntidad, name="createntidad"),
    path('create/postulacion/<pasantia>', crearPostulacion, name='postulacion'),
    path('revpost/<pasantia>', revpost,name="rev_postulacion"),
    path('revdoc/<username>', revdoc, name="rev_doc"),
    path('postulacion/registro/',crearPostulacion, name='postulacionhecha'),
    path('sorteo/<pasantia>/', sorteo, name="sorteo"),
    path('<pasantia>/unidades', registrarunidades, name="registrounidades"),
    path('<pasantia>/unidades/<id>', registrarestudiantes, name="asignarestudiantes"),
    path('view/pdf/<body>/', pdfpasantia, name="verpdf"),
]

pasantia/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
import os
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()

OPTIONS = (
    ('REVISION','REVISION'),
    ('FINALIZADO','FINALIZADO'),
)

OPTIONS_UNIDAD = (
    ('REVISION','REVISION'),
    ('ASIGNADO','ASIGNADO'),
)

OPTIONS_ESTADO = (
    ('REVISION','REVISION'),
    ('FINALIZADO','FINALIZADO'),
    ('ASIGNADO', 'ASIGNADO')
)

OPTIONS_EST = (
    ('RECHAZADO','RECHAZADO'),
    ('PENDIENTE','PENDIENTE'),
    ('ACEPTADO','ACEPTADO'),
    ('ASIGNADO','ASIGNADO'),
)

def user_directory_path_file(instance, filename):
    profile_picture_name = 'postpasantias/{0}.pdf'.format(instance.body)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_picture_name)
    
    if os.path.exists(full_path):
        os.remove(full_path)
        
    return profile_picture_name

def entidad_directory_path(instance, filename):
    profile_picture_name = 'entidades/{0}.jpg'.format(instance.nombre)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_picture_name)
    
    if os.path.exists(full_path):
        os.remove(full_path)
        
    return profile_picture_name

class Entidad(models.Model):
    nombre = models.CharField(max_length=100, blank=True, unique=True)
    image = models.ImageField(upload_to=entidad_directory_path, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class PostPasantias(models.Model):
    body=models.CharField(max_length=50, unique=True)
    cantidad = models.PositiveIntegerField(default=1)
    fecha_limite = models.DateTimeField()
    created_on = models.DateTimeField(default=timezone.now, blank=True)
    file = models.FileField(upload_to=user_directory_path_file)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    cantidad_insc = models.PositiveIntegerField(default=0)
    entidad_pert = models.ForeignKey(Entidad, on_delete=models.CASCADE, related_name='post')
    estado = models.CharField(max_length=20, choices=OPTIONS_ESTADO, default='REVISION')


    def __str__(self):
        return self.body

class Unidad(models.Model):
    nombre = models.CharField(max_length=100, blank=True)
    cantidad = models.PositiveIntegerField(default=1)
    entidad_pert = models.ForeignKey(Entidad, on_delete=models.CASCADE, related_name='unidad')
    pasantia_pert = models.ForeignKey(PostPasantias, on_delete=models.CASCADE, related_name='unidad')
    estado = models.CharField(max_length=20, choices=OPTIONS_UNIDAD, default='REVISION')
    
    def __str__(self):
        return f'{self.nombre} {self.pasantia_pert}'        
         
class Postulaciones(models.Model):
    estudiante = models.ForeignKey(User, on_delete=models.CASCADE)
    postpasantia = models.ForeignKey(PostPasantias, on_delete=models.DO_NOTHING)
    estadopas = models.CharField(max_length=20, choices=OPTIONS, default='REVISION')
    estadoest = models.CharField(max_length=20, choices=OPTIONS_EST, default='PENDIENTE')
    
    def __str__(self):
        return f'{self.postpasantia} {self.estudiante}'
    
    
class Postulantes_Unidad(models.Model):
    estudiante = models.ForeignKey(User, on_delete=models.CASCADE)
    unidad = models.ForeignKey(Unidad, on_delete=models.CASCADE)
    fecha_finalizacion = models.DateTimeField(default=timezone.now, blank=True)
    
    def __str__(self):
        return f'{self.estudiante} a la unidad {self.unidad}'

pasantia/forms.py
from django import forms
from .models import PostPasantias, Entidad

class PasantiaPostForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': '52/2022'
            }),
        required=True)
    fecha_limite = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}),required=True)
    created_on = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}),required=True)
    file = forms.FileField(widget=forms.FileInput(attrs={'accept':'.pdf'}),
        required=True
        )
    
    
    class Meta:
        model = PostPasantias
        fields = ['body', 'fecha_limite', 'created_on', 'file']
        

class EntidadRegisterForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(), required=True)
    image = forms.ImageField(label='Profile Picture', required=True, widget=forms.FileInput)
    
    class Meta:
        model = Entidad
        fields = ['name', 'image']

pasantia/views.py
from email import message
from multiprocessing import context
from accounts.models import Profile, User
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import TemplateView, View
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import PasantiaPostForm, EntidadRegisterForm
from .models import Entidad, PostPasantias, Postulaciones, Postulantes_Unidad, Unidad
from django.contrib import messages
from accounts.forms import DocumentUploadForm
from django.db.models import Q

import os
from django.conf import settings
from django.template.loader import get_template
from xhtml2pdf import pisa

#ES ADMIN
def esadmin(request, user, plantilla, context):
    if user.tipo == "administrador":
        return render(request, plantilla, context)
    else:
        messages.error(request, "Acceso denegado")
        return redirect('home')
    
def modecha(fecha):
    if fecha.month<10:
        if fecha.day<10:
            return f'{fecha.year}-0{fecha.month}-0{fecha.day}'
        else:
            return f'{fecha.year}-0{fecha.month}-{fecha.day}'
    else:
        if fecha.day<10:
            return f'{fecha.year}-{fecha.month}-0{fecha.day}'
        else:
            return f'{fecha.year}-{fecha.month}-{fecha.day}'
#CREAR DICCIONARIO
def pasantia_dic(pasantia):
    output={}
    output["body"]=pasantia.body
    output["cantidad"]=pasantia.cantidad
    output["entidad"]=pasantia.entidad.nombre
    
    return output
    
def estudiantes_post(estudiantes):
    output=[]
    for estudiante in estudiantes:
        output_int={}
        output_int["id"] = estudiante.id
        output_int["first_name"] = estudiante.first_name
        output_int["last_name"] = estudiante.last_name
        output_int["second_last_name"] = estudiante.second_last_name
        output_int["ci"] = estudiante.ci
        
        output.append(output_int)
    
    return output
#Estudiantes designados
def asignados(postulaciones):
    output=[]
    for postulante in postulaciones:
        output.append(postulante.estudiante)
    return output
    
#DATOS
@login_required
def HomeViewPostulacion(request):
    #View tiene dos funciones get y post 
    #para recibir informacion y get para obtenerla
    logged_in_user = request.user
    if logged_in_user.tipo == 'administrador':  
        return render(request, 'pasantia/agregar.html')
    else:
        messages.error(request, 'No tiene acceso a la pagina')
        return redirect('home')
    
class CreatePostPasantia(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        
        logged_in_user = request.user
        
        if logged_in_user.tipo == 'administrador':
        
            form = PasantiaPostForm()
            entidad = Entidad.objects.all()
            
            context={
                'entidad':entidad,
                'form':form,
            }
            return render(request, 'pasantia/createpost.html', context)
        else:
            messages.error(request, 'No tiene acceso a la pagina')
            return redirect('home')
        
    def post(self, request, *args, **kwargs):
        
        logged_in_user = request.user
        entidad = Entidad.objects.get(nombre=request.POST['entidad'])
        cantidad_unidades = request.POST['num_label']  
            
        form = PasantiaPostForm(request.POST, request.FILES)    
        
        if form.is_valid() and logged_in_user.tipo == 'administrador':
            new_post = form.save(commit=False)
            new_post.entidad_pert = entidad
            new_post.author = logged_in_user
            new_post.save()
            cantidad_total = 0
            for i in range(int(cantidad_unidades)):
                cantidad = request.POST[f'cantidad{i}']
                cantidad_total += int(cantidad)
                unidad = Unidad(nombre=request.POST[f'unidad{i}'].upper(), cantidad=cantidad, entidad_pert=entidad, pasantia_pert=new_post)
                unidad.save()
            new_post.cantidad = cantidad_total
            new_post.save()
          
            messages.success(request, 'Exito en la publicacion')
        else:
            messages.error(request, 'Ocurrio un problema intente de nuevo')
        
        return redirect('pasantia:pasantia-edit')
    
Createpostpasantia = login_required(CreatePostPasantia.as_view())

class CreateEntidad(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        
        logged_in_user = request.user
        
        if logged_in_user.tipo == 'administrador':
        
            form = EntidadRegisterForm()
            
            context={
                'form':form,
            }
            return render(request, 'pasantia/createunit.html', context)
        else:
            messages.error(request, 'No tiene acceso a la pagina')
            return redirect('home')
        
    def post(self, request, *args, **kwargs):
        
        logged_in_user = request.user
        
        form = EntidadRegisterForm(request.POST, request.FILES)
        
        if form.is_valid() and logged_in_user.tipo == 'administrador':
            nombre = form.cleaned_data.get('name')
            nombre = nombre.upper()
            imagen = form.cleaned_data.get('image')
            try:
                Entidad.objects.create(nombre=nombre, image=imagen)
                messages.success(request, 'Entidad añadida exitosamente')
            except:
                messages.error(request, f'La entidad {nombre} ya se encuentra en la BD')
                return redirect('pasantia:createntidad')
        else:
            messages.error(request, 'Ocurrio un error intente nuevamente')
        
        return redirect('pasantia:pasantia-edit')
    
createEntidad = login_required(CreateEntidad.as_view())

class ModificarPasantia(LoginRequiredMixin,View):
    def get(self, request, pasantia, *args, **kwargs):
        entidad = Entidad.objects.all()
        pasantia = PostPasantias.objects.get(body=pasantia)
        fecha_lim = modecha(pasantia.fecha_limite)
        fecha_pub =modecha(pasantia.created_on)
        context={
            'post':pasantia,
            'fecha_lim':fecha_lim,
            'fecha_cre':fecha_pub,
            'entidad':entidad,
        }
        plantilla = 'pasantia/modificarpost.html'
        representacion = esadmin(request, request.user, plantilla, context)
        return representacion
    
    def post(self, request, pasantia, *args, **kwargs):
        pasantia = PostPasantias.objects.get(body=pasantia)
        entidad = Entidad.objects.get(nombre=request.POST['entidad'])
        pasantia.entidad_pert=entidad
        unidades = Unidad.objects.filter(pasantia_pert=pasantia)
        unidades.delete()
        cantidad_unidades = request.POST['num_label']
        cantidad_total = 0
        for i in range(int(cantidad_unidades)):
            cantidad = request.POST[f'cantidad{i}']
            cantidad_total += int(cantidad)
            unidad = Unidad(nombre=request.POST[f'unidad{i}'].upper(), cantidad=cantidad, entidad_pert=entidad, pasantia_pert=pasantia)
            unidad.save()
        pasantia.cantidad = cantidad_total
        pasantia.fecha_limite=request.POST['fecha_limite']
        pasantia.created_on=request.POST['created_on']
        if request.POST['file'] != '':
            pasantia.file=request.POST['file']
        pasantia.save()
        messages.success(request, 'Modifica exitosamente')
        return redirect('home')
        
modificarPasantia = login_required(ModificarPasantia.as_view())

class CrearPostulacion(View):
    def get(self, request, pasantia,*args, **kwargs):
        
        post = PostPasantias.objects.get(body=pasantia)
        
        try:
            postulacion = Postulaciones.objects.filter(estudiante__id=request.user.id)
            postulacion = postulacion.get(estadopas='REVISION')
        except (Postulaciones.DoesNotExist):
            estado='sincambios'
            postulacion=''
        else:
            estado='encurso'
            if postulacion.postpasantia.fecha_limite < timezone.now():
                 estado='encalificacion'
        
        form = DocumentUploadForm()
        
        context={
            'postulacion':postulacion,
            'estado':estado,
            'pasantia':post,
            'form':form,
        }
         
        return render(request, 'pasantia/postulacion.html', context)
    
    def post(self, request, pasantia,*args, **kwargs):
        
        post = PostPasantias.objects.get(body=pasantia)
        
        if post.fecha_limite < timezone.now():
            messages.error(request, 'La postulacion ya llego a su dia limite')
            return redirect('home')
        
        logged_in_user = request.user
        try:
            postulacion = Postulaciones.objects.filter(estudiante__id=logged_in_user.id)
            postulacion = postulacion.get(estadopas='REVISION')
        except (Postulaciones.DoesNotExist):
            new_postulacion = Postulaciones(estudiante=logged_in_user, postpasantia=post)
            post.cantidad_insc += 1
            post.save()
            new_postulacion.save()
            messages.success(request, 'Registro Aceptado')
            return redirect('home')
        else:
            
            messages.success(request, f'Ya te encuentras Postulando a una pasantia {postulacion.postpasantia}')
        
            return redirect('home')

crearPostulacion = login_required(CrearPostulacion.as_view())  

#PARA TRABAJO DIRIGIDO
class Sorteo(View):
    def get(self, request, pasantia,*args, **kwargs):
        estudiantes = User.objects.filter(tipo="estudiante")
        post_est_acep = asignados(Postulaciones.objects.filter(estadoest='ACEPTADO'))

templates/pasantia/agregar.html
{% extends 'users/base.html' %}
{% block tittle %}Agregar{% endblock tittle %}
{% block content %}
<main>
    <div id="caja_presentacion" class="fila">
        <div class="llenar">
            <div class="formu"><a href="{% url 'pasantia:createpost' %}">Publicar Pasantia</a></div>    
        </div>
        <div class="llenar">
            <div class="formu"><a href="{% url 'pasantia:createntidad' %}">Añadir Unidad</a></div>    
        </div>
    </div>
</main>
{% endblock content %}

templates/pasantia/createunit.html
{% extends 'users/base.html' %}
{% block tittle %}Crear Entidad{% endblock tittle %}
{% block content %}
<main>
<div id="caja_presentacion" class="fila">
<div class="llenar">
    <div class="titulo">Nueva Unidad</div>
    <div class="formu">
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <label for="ci">
                <span>Nombre de la Unidad </span>
                {{form.name}}
            </label>
            <label for="ci">
                <span>Logo de la Unidad</span>
                {{form.image}}
            </label>
            <a ><button type="submit"> Guardar Unidad</button></a>
        </form>
    </div>
</div>
</div>
</main>
{% endblock content %}

templates/pasantia/estado.html
{% extends 'users/base.html' %}

{% block tittle %}Estado Pasantia{% endblock tittle %}

{% block content %}
<div id="caja_presentacion">
            
    <div class="espera">
        <div class="anillo"></div>
        <div class="anillo"></div>
        <div class="anillo"></div>
        <p>Esperando para revision.
            Pasantia 50</p>
    </div>
    <div class="anuncio verde">
        <p>Felicidades fuiste elegido para la pasantia presenta tus documentos en fisico</p>
    </div>
    <div class="anuncio rojo">
        <p>Lo sentimos... otra persona fue elegida no te desanimes y sigue postulando</p>
    </div>
    <div class="anuncio">
        <p>Animate a postular a una pasantia solo tienes que subir tus documentos</p>
    </div>
</div>
{% endblock content %}

templates/pasantia/modificarpost.html
{% extends 'users/base.html' %}
{% block tittle %}Publicar pasantia{% endblock tittle %}
{% block content %}
<div id="caja_presentacion" class="fila">
    <div class="llenar">
        <div class="titulo">Nueva Pasantia</div>
        <div class="formu">
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <label>
                    <span>Nro:</span>
                    <input type="text" name="body" placeholder="52/2022" required id="id_body" value={{post.body}}>
                </label>
                <label for="fecha_limite">
                    <span>Fecha Limite</span>
                    <input type="date" name="fecha_limite" required id="id_fecha_limite" value={{fecha_lim}}>
                </label>
                <label for="fecha_publicacion">
                    <span>Fecha de Publicacion</span>
                    <input type="date" name="created_on" required id="id_created_on" value={{fecha_cre}}>
                </label>
                <label for="entidad">
                    <span>Entidad</span>
                    <input list="entidades" name="entidad" id="entidad" required value={{post.entidad_pert}}>
                    <datalist id="entidades">
                        {% for enti in entidad %}
                        <option value="{{enti.nombre}}">
                        {% endfor %}    
                </label>
                <div id="unidades" style="padding:0px 0px 0px 0px;">
                    <label for="unidad" class="aux_label">
                        <span>Unidad</span>
                        <div class="d_auc">
                            <input oninput="lista_dinamica()" type="text" name="unidad0" id="unidad" placeholder="Elige una Unidad" style="width:100% ; height:35px; margin-bottom: 10px;" value="">
                            <input type="number" name="cantidad0" id="cantidad" placeholder="Cantidad Puestos" style="width:100% ;height:35px; " min="1" >
                        </div>
        
                    </label>
                    
                </div>
                <a class="btn_a oculto" onclick="una_mas()" id="btn_agregar">Agregar Unidad</a>
                <a class="btn_a oculto" onclick="una_menos()" id="btn_desagregar">Quitar Unidad</a>
                <input type="hidden" name="num_label" id="num_label" value="1">
                <label for="log_uni">
                    <a href={{post.file.url}}><span>Convocatoria PDF</span></a>
                    <input type="file" name="file" accept=".pdf" id="id_file">
                </label>
                <a><button type="submit">Modificar Pasantia</button> </a>
            </form>
        </div>
    </div>
</div>
</main>
<script>
var c=1;
function lista_dinamica(){
    /*
    var d = document.getElementById("unidadesL").childNodes;
    for (let i = 1; i < d.length; i++) {
        if(d[i].value==a){
            d[i].remove();
        }
    }*/
    var e=document.getElementById("btn_agregar");
    e.className="btn_a";
    /*
    if(c-1<d.length){
        var e=document.getElementById("btn_agregar");
        e.className="btn_agregar";
    }else{
        var g=document.querySelector(".spanito");
        g.className="spanito";
    }*/
    
}
function una_mas(){
    var nom="unidad" + c;
    const n_L= document.createElement("label");
    n_L.setAttribute("for",nom);
    n_L.setAttribute("class","aux_label");
    const n_S= document.createElement("span");
    n_S.textContent="Unidad "+c;
    n_L.appendChild(n_S);
    const n_D=document.createElement("div");
    n_D.setAttribute("class","d_auc");
    const n_I= document.createElement("input");
    n_I.setAttribute("oninput","lista_dinamica()");
    n_I.setAttribute("list","unidadesL");
    n_I.setAttribute("name",nom);
    n_I.setAttribute("id",nom);
    n_I.setAttribute("placeholder","Elige una Unidad");
    n_I.setAttribute("style","width:100% ;height:35px; margin-bottom: 10px;");
    n_D.appendChild(n_I);
    const n_C= document.createElement("input");
    n_C.setAttribute("type","number");
    n_C.setAttribute("name","cantidad"+c);
    n_C.setAttribute("id","cantidad"+c);
    n_C.setAttribute("placeholder","Cantidad Puestos");
    n_C.setAttribute("style","width:100% ;height:35px;");
    n_D.appendChild(n_C);n_L.appendChild(n_D);
    c++;
    document.getElementById("unidades").appendChild(n_L);
    var ay=document.getElementById("btn_agregar");
    ay.className+=" oculto";
    var ta = document.getElementById("btn_desagregar");
    ta.className="btn_a";

    var g=document.getElementById("num_label");
    g.value=c;
}

function una_menos(){
    var qwe = document.querySelectorAll(".aux_label");
    var as=qwe.length-1;
    qwe[as].remove();
    c--;
    if(c==1){
        var ta = document.getElementById("btn_desagregar");
        ta.className="btn_a oculto";
    }
    lista_dinamica();
    var g=document.getElementById("num_label");
    g.value=c;
}
</script>
{% endblock content %}

templates/pasantia/postulacion.html
{% extends 'users/base.html' %}
{% block tittle %}Postulacion {{pasantia.body}}{% endblock tittle %}

{% block content %}
<main>
    <div id="caja_presentacion" class="fila">
        {% if estado == 'encalificacion' %}
        <div class="postulacion">
            <div class="titulo">
                Aviso de postulación
            </div>
            <div class="contenido">
                <span>Se encuentra inscrito en la pasantia {{postulacion.postpasantia}} se estan calificando sus documentos</span> 
            </div>
        </div>
        <br/>
        {% else %}
            {% if estado == 'encurso' %}
            <div class="postulacion">
                <div class="titulo">
                    Aviso de postulación
                </div>
                <div class="contenido">
                    <span>Se encuentra inscrito en la pasantia {{postulacion.postpasantia}} tiene hasta la fecha {{postulacion.postpasantia.fecha_limite}}</span> 
                    <span>para modificar sus datos, posteriormente se restringira el cambio a los documentos</span>
                </div>
            </div>
            <br/>
            {% else %}
            <div class="postulacion">
                <div class="titulo">
                    Aviso de postulación
                </div>
                <div class="contenido">
                    <span>La Pasantia {{pasantia.body}}</span>
                <span>Revisa bien los documentos e informacion proporciona en esta pagina</span>
                <span>Una vez postulado solo podras hacer modificaciones hasta antes de la fecha limite</span>
                <span>No podras postularte a otra pasantia mientras tus documentos estén en espera</span>
                <span>Ni tampoco una vez seas elegido para una pasantia</span>
                <form method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Postularme" />
                </form>
                
                </div>
            </div>
            <br/>
            {% endif %}  
            <div id="documentos_estudiante" class="llenar">
                <div class="titulo">
                    Documentos Personales
                </div>
                    <div class="formu">
                        <form method='POST' enctype="multipart/form-data" action="{% url 'users:profile-document' %}">
                            {% csrf_token %}
                            <label for="ci" class="verificado {{user.profile.est_ci}}">
                                
                                {% if user.profile.est_ci != 'rechazado' %}
                                <a href="{{user.profile.ci_doc.url}}"><span>Fotocopia de Carnet de Identidad</span></a>
                                {% else %}
                                <span>Fotocopia de Carnet de Identidad</span>
                                {% endif %}
                                {{form.ci_doc}}
                            </label>
                            <label for="hoja_vida" class="verificado {{user.profile.est_hoja_vida}}">
                                {% if user.profile.est_hoja_vida != 'rechazado' %}
                                <a href="{{user.profile.hoja_vida.url}}"><span>Hoja de vida documentado</span></a>
                                {% else %}
                                <span>Hoja de vida documentado</span>
                                {% endif %}
                                {{form.hoja_vida_doc}}
                            </label>
                            <label for="record" class="verificado {{user.profile.est_record_doc}}">
                                {% if user.profile.est_record_doc != 'rechazado' %}
                                <a href="{{user.profile.record_doc.url}}"><span>Historial y record academico</span></a>
                                {% else %}
                                <span>Historial y Record academico</span>
                                {% endif %}
                                {{form.record_doc}}
                            </label>
                            <label for="matri" class="verificado {{user.profile.est_bol_insc}}">
                                {% if user.profile.est_bol_insc != 'rechazado' %}
                                <a href="{{user.profile.bol_insc.url}}"><span>Boleta de Inscripcion</span></a>
                                {% else %}
                                <span>Boleta de Inscripcion</span>
                                {% endif %}
                                {{form.bol_insc_doc}}
                            </label>
                            <label for="ce" class="verificado {{user.profile.est_conc_est}}">
                                {% if user.profile.est_conc_est != 'rechazado' %}
                                <a href="{{user.profile.conc_est.url}}"><span>Certificado de Conclusion de estudios</span></a>
                                {% else %}
                                <span>Certificado de Conclusion de estudios</span>
                                {% endif %}
                                {{form.conc_est_doc}}
                            </label>
                            <a><button type="submit">Guardar Cambios</button></a>
                        </form>
                </div>
            </div>
            <br>
            {% endif %}
    </div>
</main>
{% endblock content %}