accounts/urls.py
from django.urls import path

from .views import *

app_name = "accounts"

urlpatterns = [
    path('profile/edit', EditProfile, name="edit"),
    path('profile/documents', DocumentUploadProfile, name="profile-document"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pasantia/', include('pasantia.urls', namespace="pasantia")),
    path('users/', include('accounts.urls', namespace="users")),
    path('', HomeView, name='home'),
    path('informacion/<post>/', viewInformation, name="info"),
    path('finalizados/post', postfinalizados, name="postfinalizados"),
    path('buscador/',buscador, name="buscador")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pasantia/urls.py
from django.urls import path

from .views import *

app_name = "pasantia"

urlpatterns = [
    path('create/post', HomeViewPostulacion, name="pasantia-edit"),
    path('create/postpasantia', Createpostpasantia, name='createpost'),
    path('modify/<pasantia>/', modificarPasantia, name="modpost"),
    path('create/registentidad',createEntidad, name="createntidad"),
    path('create/postulacion/<pasantia>', crearPostulacion, name='postulacion'),
    path('revpost/<pasantia>', revpost,name="rev_postulacion"),
    path('revdoc/<username>', revdoc, name="rev_doc"),
    path('postulacion/registro/',crearPostulacion, name='postulacionhecha'),
    path('sorteo/<pasantia>/', sorteo, name="sorteo"),
    path('<pasantia>/unidades', registrarunidades, name="registrounidades"),
    path('<pasantia>/unidades/<id>', registrarestudiantes, name="asignarestudiantes"),
    path('view/pdf/<body>/', pdfpasantia, name="verpdf"),
]

templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="icon" href="{% static 'images/u_logo.png' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <link rel="stylesheet" href="{% static 'css/styleT.css' %}">
    <title>{% block tittle %}{% endblock tittle %}</title>

    <!--Boxicons-->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    {% block head %}{% endblock head %}
</head>

<body>
    {% include 'users/header.html' %}
    {% include 'messages.html' %}
    {% block content %}{% endblock content %}
    
    {% include 'components/footer.html' %}
    
</body>

</html>

templates/users/document.html
{% extends 'users/base.html' %}

{% block tittle %}Documentos {{user.username}}{% endblock tittle %}



{% block content %}
<main>
    <div id="caja_presentacion" class="fila">
        {% if estado == 'encalificacion' %}
        <div class="postulacion">
            <div class="titulo">
                Aviso de postulación
            </div>
            <div class="contenido">
                <span>Se encuentra inscrito en la pasantia {{postulacion.postpasantia}} se estan calificando sus documentos</span> 
            </div>
        </div>
        <br/>
        
        {% else %}
            {% if estado == 'encurso' %}
            <div class="postulacion">
                <div class="titulo">
                    Aviso de postulación
                </div>
                <div class="contenido">
                    <span>Se encuentra inscrito en la pasantia {{postulacion.postpasantia}} tiene hasta la fecha {{postulacion.postpasantia.fecha_limite}}</span> 
                    <span>para modificar sus datos, posteriormente se restringira el cambio a los documentos</span>
                </div>
            </div>
            <br/>
            {% endif %}
            <div id="documentos_estudiante" class="llenar">
                <div class="titulo">
                    Documentos Personales
                </div>
                    <div class="formu">
                        <form method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            <label for="ci" class="verificado {{user.profile.est_ci}}">
                                <span>Fotocopia de Carnet de Identidad</span>
                                {{form.ci_doc}}
                            </label>
                            <label for="hoja_vida" class="verificado {{user.profile.est_hoja_vida}}">
                                <span>Hoja de vida documentado</span>
                                {{form.hoja_vida_doc}}
                            </label>
                            <label for="record" class="verificado {{user.profile.est_record_doc}}">
                                <span>Historial y record academico</span>
                                {{form.record_doc}}
                            </label>
                            <label for="matri" class="verificado {{user.profile.est_bol_insc}}">
                                <span>Boleta de Inscripcion o Fotocopia Matricula</span>
                                {{form.bol_insc_doc}}
                            </label>
                            <label for="ce" class="verificado {{user.profile.est_conc_est}}">
                                <span>Certificado de Conclucion de estudios</span>
                                {{form.conc_est_doc}}
                            </label>
                            <a><button type="submit">Guardar Cambios</button></a>
                        </form>
                </div>
            </div>
            <br>
        {% endif %}
            
    </div>
</main>
{% endblock content %}

templates/users/edit.html
{% extends 'users/base.html' %}

{% block tittle %}Configuracion {{user.username}}{% endblock tittle %}

{% block content %}
<main>
    <div id="caja_presentacion" class="fila">
            <div id="datos_estudiante" class="llenar">    
                <div class="titulo">
                    Datos Personales
                </div>
                <div class="formu">
                    <form method="POST" enctype="multipart/form-data">
                        <br>
                        {% csrf_token %}
                        <label for="nombre">
                            <span>Nombres:</span>
                            <input type="text" id="nombre" value=" {{user.first_name}}" readonly>
                        </label>
                        <label for="a_paterno">
                            <span>Apellido Paterno:</span>
                            <input type="text" id="a_paterno" value=" {{user.last_name}}" readonly>
                        </label>
                        <label for="a_materno">
                            <span>Apellido Materno:</span>
                            <input type="text" id="a_materno" value=" {{user.second_last_name}}" readonly>
                        </label>
                        <label for="carnet">
                            <span>Carnet:</span>
                            <input type="text" id="carnet" value=" {{user.ci}}" readonly>
                        </label>
                        <label for="ru">
                            <span>RU:</span>
                            <input type="text" id="ru" value=" {{user.username}}" readonly>
                        </label>
                        <label for="">
                            <span>Celular:</span>
                            {{form.celular}}
                        </label>
                        <a><button type="submit">Guardar Cambios</button> </a>
                        
                        <br>
                    </form>
                    <a class="button secondaryAction" href="{% url 'account_change_password' %}">Cambiar contraseña</a>
                    <br/>
                    <a class="button secondaryAction" href="{% url 'account_email' %}">Cambiar e-mail</a>
                </div>
            </div>

    </div>
</main>
{% endblock content %}

templates/users/header.html
{% load static %}
<header>
    <div id="logos">
        <div class="logo">
            <img id="umsa" src="{% static 'images/u_logo.png' %}" alt="Logo">
        </div>
        <div>
            <h1>
                SISTEMA DE PASANTIAS
            </h1>
        </div>
        <div class="logo">
            <img id="conta" src="{% static 'images/logo.png' %}" alt="Logo">
        </div>
    </div>
    <div id="nav_men">
        <div id="bus">
            <label for="btn-b" class="label_esp">
            <a>
                <ion-icon name="search-outline"></ion-icon>
            </a>
            </label>
            <input type="text" name="bus_sup" id="bus_sup" class="b_s" value="">
        </div>
        <div id="central">
            <ul>
                <li class="list">
                    <a href="{% url 'home' %}" id="aux">
                        <span class="i">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="txt">Principal</span>
                    </a>
                </li>
                
                {% if user.tipo == 'administrador'%}
                <li class="list">
                    <a href="./ver_post.html" id="aux">
                        <span class="i">
                            <ion-icon name="people-outline"></ion-icon >
                        </span>
                        <span class="txt">Postulados</span>
                    </a>
                </li>
                {% else %}
               
                <li class="list  ">
                    <a href="./postulacion3.html" id="aux">
                        <span class="i">
                            <ion-icon name="bookmark-outline"></ion-icon>
                        </span>
                        <span class="txt">Postulacion</span>
                    </a>
                </li>
                {% endif %}
                <div class="indicador oculto"></div>
            </ul>
        </div>

        <div id="not">
            <div id="notifica" class="notifica">
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
                <span>
                    Esta es una notificacion que aparece cuado le das click al boton de la campana
                </span>
            </div>
            <div id="min_men" class="min_men">
                
               
                {% if user.profile %}
                <a href="{% url 'users:profile-document' %}" class="ind">Documentos</a>
                <a href="{% url 'users:edit' %}" class="ind">Configuracion</a>
                {% else %}
                <a href="{% url 'pasantia:pasantia-edit' %}" class="ind">Agregar</a>
                <a href="{% url 'account_change_password' %}" class="ind">Configuracion</a>
                {% endif %}
                <a href="{% url 'account_logout' %}" class="ind">Salir</a>
            </div>
            <a onclick="miPer()"><ion-icon name="notifications-outline"></ion-icon></a>
            <a onclick="miNot()"><ion-icon name="person"></ion-icon></a> 
        </div>
        <script>
            /*
            const list=document.querySelectorAll('.list');
            function activeLink(){
                list.forEach((item)=>
                item.classList.remove('active'));
                this.classList.add('active');
            }
            list.forEach((item)=>
            item.addEventListener('click',activeLink));
            */
            function miPer() {
                var x = document.getElementById("notifica");
                var y = document.getElementById("min_men");
                if (x.className === "notifica") {
                    if(y.className === "min_men"){
                        x.className += " responsive";
                    }else{
                        y.className = "min_men";
                        x.className += " responsive";
                    }
                    
                } else {
                    x.className = "notifica";
                }
            }
            function miNot() {
                var x = document.getElementById("min_men");
                var y = document.getElementById("notifica");
                if (x.className === "min_men") {
                    if(y.className === "notifica"){
                        x.className = "min_men";
                    }else{
                        y.className="notifica";
                        x.className = "min_men";
                    }
                    x.className += " res";
                } else {
                    x.className = "min_men";
                }
            }
        </script>
        
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </div>
</header>